version: "3.8"

services:
  db:
    image: postgres:16          # 최신 대신 안정적 버전 명시
    container_name: paranote_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paranote
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
